### ISSUE TITLE
missing parameter for run command in README

### ISSUE THREAD

**Issue by youngstudent2** [DeepSoftwareAnalytics/CodeSumEvaluation#1]
Dear author,
when running ```bash run_tlcodesum.sh 0```, there is an error:
```
run.py: error: argument --seed: expected one argument
```
in `run_tlcodesum.sh` line 50: ```seed=$2``` seems missing
is that serious？
Thanks in advance

**Comment by youngstudent2** [comment]
the README is in Deepcom_Reimplement

**Comment by s1530129650** [comment]
Thanks. We have updated the `README` in Deepcom_Reimplement.
We ran the experiment three times in the paper with random seed 0,1,2, thus we set `seed` as an argument for convenience.

**Comment by youngstudent2** [comment]
Thanks for your update 😄
